[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "certifi>=2020.06.20",
    "oldest-supported-numpy",
    "pybind11>=2.6",
    "setuptools_scm>=7",
]


[tool.isort]
known_mpltoolkits = "mpl_toolkits"
known_pydata = "numpy, matplotlib.pyplot"
known_firstparty = "matplotlib"
sections = "FUTURE,STDLIB,THIRDPARTY,PYDATA,FIRSTPARTY,MPLTOOLKITS,LOCALFOLDER"
no_lines_before = "MPLTOOLKITS"
force_sort_within_sections = true
